### ISSUE TITLE
DrawOrder does not work

### ISSUE THREAD

**Issue by Stee92** [bendmorris/spinehaxe#16]
See SkeletonJson.hx line 327:
var drawOrderValues:Dynamic = map.getNode("draworder");

In the latest spine exports the nodes are called "drawOrder" instead of "draworder".

**Comment by bendmorris** [comment]
Are you using the latest version? 

https://github.com/bendmorris/spinehaxe/blob/master/spinehaxe/SkeletonJson.hx#L485

It looks for "drawOrder" first and only falls back on "draworder" if it isn't found, which is the same behavior as the AS3 runtime.

**Comment by Stee92** [comment]
Yeah you are right.. it was my fault. I'm sorry!
