### ISSUE TITLE
Openfl version

### ISSUE THREAD

**Issue by bmfs** [bendmorris/spinehaxe#23]
Which openfl version is supported?

**Comment by bendmorris** [comment]
Good question. Right now the OpenFL renderer is referencing Tilesheet which was removed in OpenFL 4. Looks like it's only using constants though, so it shouldn't be too hard to remove.

**Comment by bendmorris** [comment]
Just pushed an update tested to work with the latest OpenFL/Lime versions, NME, and flash. Unfortunately it seems OpenFL removed support for color from drawTriangles, so there's no longer color support in the reference renderer when using OpenFL.
